version: '1'
services:
  microservicio:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    environment:
     - spring.datasource.url=jdbc:oracle:thin:@zz4zym3bu0ucvq7r_high?TNS_ADMIN=/app/oracle_wallet/
     - spring.datasource.username=ADMIN
     - spring.datasource.password=OracleCloud123
    restart: always